// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package org.enterprisedlt.fabric.proto;

public interface TestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:contract.TestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 intValue = 2;</code>
   */
  int getIntValue();
}
